name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        component: [api, web, worker]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js (for web)
      if: matrix.component == 'web'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: apps/web/package-lock.json
    
    - name: Setup Python (for api and worker)
      if: matrix.component != 'web'
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Node.js dependency scan
    - name: Run npm audit (web)
      if: matrix.component == 'web'
      run: |
        cd apps/web
        npm audit --audit-level moderate
    
    # Python dependency scan
    - name: Install safety
      if: matrix.component != 'web'
      run: pip install safety
    
    - name: Run safety check
      if: matrix.component != 'web'
      run: |
        cd ${{ matrix.component == 'api' && 'apps/api' || 'worker' }}
        safety check -r requirements.txt

  secret-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

  container-scan:
    runs-on: ubuntu-latest
    needs: [dependency-scan]
    if: github.event_name == 'push'
    
    strategy:
      matrix:
        component: [api, worker]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image
      run: |
        cd ${{ matrix.component == 'api' && 'apps/api' || 'worker' }}
        docker build -t judgelab-${{ matrix.component }}:test .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'judgelab-${{ matrix.component }}:test'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=judgelab
          -Dsonar.projectKey=judgelab_judgelab
          -Dsonar.sources=apps/api,apps/web,worker
          -Dsonar.exclusions=**/*test*/**,**/*.test.*
          -Dsonar.python.coverage.reportPaths=coverage.xml